FROM golang:1.25-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache make git

# Copy dependency files
COPY go.mod go.sum ./
RUN go mod download

# Copy project files
COPY . .

# Run migration
CMD ["make", "migrate"]
